name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend and Backend to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |

          # Connect to the EC2 instance and deploy
          cd /
          sudo touch server-login.pem
          sudo sh -c "echo '$SSH_PRIVATE_KEY' > /server-login.pem"
          ssh -i "server-login.pem" ubuntu@ec2-13-203-77-47.ap-south-1.compute.amazonaws.com << 'EOF'
          echo "Starting deployment..."

          # Deploy backend
          echo "Deploying backend..."
          cd /home/ubuntu/test/Shopsy/backend/
          git fetch origin master
          git reset --hard origin/master
          npm install
          pm2 restart /home/ubuntu/test/Shopsy/backend/index.js

          # Deploy frontend
          echo "Deploying frontend..."
          cd /home/ubuntu/test/Shopsy/frontend/
          git fetch origin master
          git reset --hard origin/master
          npm install
          npm run build
          serve -s /home/ubuntu/test/Shopsy/frontend/build/  # Replace with your frontend deployment directory

          echo "Deployment complete."
          EOF
