name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend and Backend to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |

          # Connect to the EC2 instance and deploy
          sudo touch ~/server-login.pem
          echo "$SSH_PRIVATE_KEY" > /tmp/server-login.pem
          chmod 600 /tmp/server-login.pem

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Disable host key verification
          echo "Host ec2-43-204-130-189.ap-south-1.compute.amazonaws.com
                StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Connect to the EC2 instance and deploy
          ssh -tt -i "/tmp/server-login.pem" ubuntu@ec2-43-204-130-189.ap-south-1.compute.amazonaws.com << 'EOF'
          set -e  # Stop execution on remote script errors

          # Deploy backend
          echo "Deploying backend..."
          echo "Changed Directory..."
          cd /home/ubuntu/test/Shopsy/backend/
          echo "Fetching master..."
          git fetch origin master
          echo "Resetting branch..."
          git reset --hard origin/master
          echo "Installing Packages"
          npm install
          echo "Restarting BE"
          pm2 restart /home/ubuntu/test/Shopsy/backend/index.js

          # Deploy frontend
          echo "Deploying frontend..."
          echo "Changed Directory..."
          cd /home/ubuntu/test/Shopsy/frontend/
          echo "Fetching master..."
          git fetch origin master
          echo "REsetting branch..."
          git reset --hard origin/master
          echo "Installing Packages"
          npm install
          echo "Building FE"
          npm run build
          echo "Serving FE"
          serve -s /home/ubuntu/test/Shopsy/frontend/build/  # Replace with your frontend deployment directory

          echo "Deployment complete."
          EOF
