name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    outputs:
      ssh_key_path: ${{ steps.setup.outputs.ssh_key_path }}
    steps:
      - name: Setup SSH Key and Config
        id: setup
        run: |
          echo "Setting up SSH configuration..."
          sudo touch ~/server-login.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/server-login.pem
          chmod 600 /tmp/server-login.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "Host ec2-15-206-189-217.ap-south-1.compute.amazonaws.com
                StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          echo "/tmp/server-login.pem" # Output the path for reuse

  deploy-backend:
    if: ${{ contains(github.event.commits.*.modified, 'backend/**') }}
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend
        run: |
          ssh -tt -i "/tmp/server-login.pem" ubuntu@ec2-15-206-189-217.ap-south-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/test/Shopsy/backend/
          git fetch origin master
          git reset --hard origin/master
          npm install
          pm2 restart /home/ubuntu/test/Shopsy/backend/index.js
          exit
          EOF

  deploy-frontend:
    if: ${{ contains(github.event.commits.*.modified, 'frontend/**') }}
    needs: setup-ssh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        run: |
          ssh -tt -i "/tmp/server-login.pem" ubuntu@ec2-15-206-189-217.ap-south-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/test/Shopsy/frontend/
          git fetch origin master
          git reset --hard origin/master
          npm install --legacy-peer-deps
          npm run build
          serve -s build
          exit
          EOF